'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CMC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_cascade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_cascade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_view_tile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_view_tile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_join() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_join", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cmc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connect1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connect2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connect3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connect4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_google() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_google", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_16_admgr_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_16_admgr_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_16_log_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_16_log_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_16_logclear_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_16_logclear_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_16_netdrv_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_16_netdrv_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_16_pin_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_16_pin_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_16_ptr_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_16_ptr_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_16_sw_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_16_sw_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_16_telnet_t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_16_telnet_t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_28_event_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_28_event_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_28_perf_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_28_perf_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_28_rdp_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_28_rdp_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_28_reg_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_28_reg_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_28_users_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_28_users_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_28_zen_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_28_zen_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_graph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_graph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_arrow_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_arrow_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_clear_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_clear_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_cogB_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_cogB_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_cogB_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_cogB_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_copy_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_copy_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_delete_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_delete_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_lck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_lck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_msg_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_msg_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_nwk1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_nwk1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_pc_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_pc_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_ref_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_ref_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_reg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_reg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_share_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_share_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_svc_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_svc_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_svc_green_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_svc_green_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_svc_green_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_svc_green_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_tools_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_tools_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_usegr_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_usegr_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_user_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_user_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_userpc_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_userpc_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_t_usersG_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_t_usersG_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_evnt_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_evnt_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_mgmt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_mgmt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_perf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_perf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_PWR_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_PWR_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_rdp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_rdp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_reg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_reg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_usrs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_usrs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_usrs_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_usrs_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_vnc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_vnc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property png_w_zen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("png_w_zen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property regedit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("regedit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wrench() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wrench", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
