'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CMC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _0029() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0029", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_cascade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_cascade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_form() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_form", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_get() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_get", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_osx_terminal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_osx_terminal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_view_tile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_view_tile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_join() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_join", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bullet_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chart_accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart_accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chart1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer_accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer_link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer_remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property door_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("door_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property drive_network() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drive_network", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exclamation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exclamation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property group_key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("group_key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor_lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor_lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property package_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picture_key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picture_key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property regedit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("regedit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property server() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stats_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stats_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table_gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user-16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_info_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user-info-16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_suit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_suit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Utilities_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Utilities-32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vnclogo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vnclogo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wrench() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wrench", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wrench_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wrench_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
